# Generated by Django 5.2.1 on 2025-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cake',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
