# Generated by Django 5.2.1 on 2025-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(through='main_app.OrderItem', to='main_app.cake'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('cake', 'order')},
        ),
    ]
