# Generated by Django 5.2.1 on 2025-05-23 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_cakes_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
            ],
            options={
                'unique_together': {('cake', 'customer')},
            },
        ),
    ]
