# Generated by Django 5.2.1 on 2025-05-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cakerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cake_ratings',
            field=models.ManyToManyField(through='main_app.CakeRating', to='main_app.cake'),
        ),
    ]
