# Generated by Django 5.2.1 on 2025-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer_cake_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('flavor', models.CharField(max_length=20)),
                ('country_of_origin', models.CharField(max_length=30)),
            ],
        ),
    ]
