# Generated by Django 5.2.1 on 2025-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
