# Generated by Django 5.2.1 on 2025-05-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cake_cake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='cake',
            new_name='ingredients',
        ),
    ]
